export {Dashboard} from './Dashboard/Dashboard';
export {Home} from './Home/Home';
export {Login} from './Login/Login'
export {SignUp} from './SignUp/SignUp';
export {Logout} from './Logout/Logout';
export {Profile} from './Profile/Profile';
export {NotFound} from './NotFound/NotFound';
export {Explore} from './Explore/Explore';
export {Notifications} from './Notifications/Notifications';
export {Bookmarks} from './Bookmarks/Bookmarks';
export {Main} from './Main/Main';